### ISSUE TITLE
Compiled images (on github pages) not working as expected

### ISSUE THREAD

**Issue by rominronin** [hydephp/framework#588]
The image on the following page has tearing artefacts (the two lines streaking across the image):
https://rominronin.github.io/posts/2023/podcasting

The original image doesn't have these lines.

On the following page, the image is broken:
https://rominronin.github.io/posts/2023/new-website

I'm using the github actions from the blog post:
https://hydephp.com/posts/github-actions-deployment

Is this related to HydePHP or github pages? Any ideas what's causing this or how to overcome it? Thanks

**Comment by caendesilva** [comment]
Hey there! Thanks for making this post. A few days ago, another HydePHP (@sunderee) user had issues with committing images GitHub. For him, the images just got fully corrupted so I'm not sure it is related as your issue looks different on the surface. I think the way he solved it was by uploading them through the GitHub Web UI. 

I'm going to be fully honest here: I don't have any idea at the moment as to what is going on. The way Hyde transfers images from the `_media/` directory to `_site/media` is using the built-in PHP `copy` function, and I have a hard time seeing how such a core language feature would be corrupting images.


Okay, I'm looking at the source code for your website, and I see that trying to view the files on the Web UI has the same issue. One is corrupted like it was for Sunderee, and the others have the same lines. **So I think something is going wrong when pushing/committingthe images go GitHub**

I do not think this is an issue with Hyde, but I think we can keep this issue open for a while as I have a vested interest in seeing this solved. I would presume something is going wrong when the images are being transferred to GitHub. So this is most likely a problem with GitHub itself as the issue happens before the site build and deployment.

How are you uploading the images? Did you do it through the Web UI or via `git add` and `git push`? This would help me find any links with Sunderee's issue.

**Comment by caendesilva** [comment]
Could you try adding `*.png binary` to the `.gitattributes` file? (Then if needed, force-recommit with `git add *.png --force)`

If that doesn't help and if you are on Unix system, can you try running the `file` command and send me the first 10 lines of binary data? I want to compare it to the corrupted lines. 

I'm thinking this might be related to https://stackoverflow.com/questions/19411981/images-corrupt-after-git-push, as this would track with my assumption that something went wrong with the binary data during commit. If GitHub for some reason can't tell that the image is binary, it might try to do some data normalization like CRLF to LF, which could corrupt the images.

**Comment by rominronin** [comment]
I added the entire binary portion of the .gitattributes for generic web projects to my site and pushed. The the git add --force command didn't catch any of the existing images (only one new image which is in draft).

To force a change, I removed all images from the repo, pushed, re-added images and pushed again. Same result as before.

So now I removed all images, re-exported them with new file names, this time all as .jpg files, updated the posts, pushed. Now two out of the three images are fine, and the one image has a single line going through it (I suppose it doesn't matter how it's corrupted, the important thing is: it is corrupted!).

Thanks btw for the quick response. I hope I posted this question in the right repo.

**Comment by caendesilva** [comment]
Glad to hear it mostly worked. Do you have the original podcasting image? 

I tried to fix the artifacts in Affinity. It's not perfect, but it might be better than nothing.
![podcast-cover-image](https://github.com/hydephp/framework/assets/95144705/d7b115e5-e1f0-49dc-95c2-667b70c9c19d)


I'm going to close this as completed as it seems like we figured out the issue. I'm going to transfer it to the main Hyde repository for better visibility. If people in the future stumble into this problem, please let me know, and I will consider adding the gitattributes to the base Hyde project.

Thanks for using Hyde and letting me know about this issue!
